- name: prompting variables
  hosts: node
  become: yes
  vars_prompt:
  - name: username
    prompt: enter the username
    private: true
  - name: password
    prompt: enter the password
    private: true

  tasks:
  - name: prompt checking information
    ansible.builtin.debug:
    msg: "hi, my username is: {{ username }}. password is {{ password }}"