- name: default variable
  hosts: node
  become: yes
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "my name is {{ name | default ( 'mamatha') }}"

- name: upper case
  hosts: node
  become: yes
  vars: 
    name: "i am mamatha"
  tasks:
  - name: upper
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

- name: lower case
  hosts: node
  become: yes
  vars: 
    name: "I AM MAMATHA"
  tasks:
  - name: lower
    ansible.builtin.debug:
      msg: "{{ name | lower }}"

- name: finding min and max numbers
  hosts: node
  become: yes
  vars:
    numbers: [10, 30, 40, 90]
  tasks:
  - name: find the min and max number
    ansible.builtin.debug:
      msg: "The minimum number is: {{ numbers | min }} , maximum number is:{{ numbers | max }}"


- name: removing duplicate numbers
  hosts: node
  become: yes
  vars:
    numbers: [ 10,20,20,40,50,50,90 ]
  tasks:
  - name: find duplicate num
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}" 

- name: converting dictionary to list # dict means map,item
  hosts: node
  become: yes
  vars:
    my_dict:
      Course: Devops
      Duration: 3 years
      Trainer: Mamatha
  tasks:
  - name: before convering
    ansible.builtin.debug:
      msg: " before convering {{ my_dict }}"
  - name: before convering
    ansible.builtin.debug:
      msg: " after convering {{ my_dict | dict2items }}"


- name: converting list to dictionary # dict means map,item
  hosts: node
  become: yes
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convering
    ansible.builtin.debug:
      msg: " before convering {{ my_list }}"
  - name: before convering
    ansible.builtin.debug:
      msg: " before convering {{ my_list | items2dict }}"


