- name: installing nginx
  hosts: node
  become: yes
  tasks:
  - name: nginx install
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - postfix
    - mysql

- name: installing packages
  hosts: node
  become: yes
  tasks:
  - name: installing few packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state}}"
    loop:
    - { name: 'mysql', state: 'absent'}
    - { name: 'nginx', state: 'latest'}
    - { name: 'postfix', state: 'absent'}